version: '3.9'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/flatfile-demo
    ports:
      - "8000:8000"
    environment:
      - MYSQL_NAME=mysql-db
      - MYSQL_USER=hackday2022
      - MYSQL_PASSWORD=hackday2022-password
      - MYSQL_HOST=db
    depends_on:
      - db

  db:
    image: mysql:5.6.50
    environment:
      MYSQL_ROOT_PASSWORD: hackday2022-password
      MYSQL_DATABASE: datamaster
      MYSQL_USER: hackday2022
      MYSQL_PASSWORD: hackday2022-password
    command: --max_allowed_packet=32505856
    volumes:
      - mysql-db:/var/lib/mysql
    ports:
      - 3306:3306
  
volumes:
  mysql-db: 